// tests/embed/udim-view.spec.mjs: P4d stage 2 acceptance for the Material
// Viewer's custom-geometry UDIM split (js/mtlx-engine.js's applyUdimSplit,
// wired through bindDroppedTextures -> handle.bindTextureFileMap).
// Runs against the real #!viewer engine globals, same pattern as
// displacement-view.spec.mjs. All assets (OBJ text, PNG bytes) are
// generated in this file, nothing fetched from outside the repo.

import zlib from 'node:zlib';
import { test, expect, WAIT_TIMEOUT } from './lib/test-base.mjs';

async function gotoEngine(page, embedURL) {
  await page.goto(embedURL + '/index.html#!viewer');
  await page.waitForFunction(
    () => window.getMxEnv && window.createMtlxRenderView && window.THREE,
    null, { timeout: WAIT_TIMEOUT }
  );
}

// ---- minimal 8-bit RGB PNG encoder (solid color), no external deps. ----
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(buf) {
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i++) crc = CRC_TABLE[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}
function pngChunk(type, data) {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crcBuf = Buffer.alloc(4); crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crcBuf]);
}
function solidColorPngBase64(width, height, [r, g, b]) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; ihdr[9] = 2; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0; // 8-bit RGB, no interlace
  const rowLen = 1 + width * 3;
  const raw = Buffer.alloc(rowLen * height);
  for (let y = 0; y < height; y++) {
    raw[y * rowLen] = 0;
    for (let x = 0; x < width; x++) {
      const o = y * rowLen + 1 + x * 3;
      raw[o] = r; raw[o + 1] = g; raw[o + 2] = b;
    }
  }
  const idat = zlib.deflateSync(raw);
  const buf = Buffer.concat([sig, pngChunk('IHDR', ihdr), pngChunk('IDAT', idat), pngChunk('IEND', Buffer.alloc(0))]);
  return buf.toString('base64');
}

// Two disjoint quads (no shared vertices, so no vertex-sharing assumptions
// needed either way): the first spans UDIM tile 1001 (u 0..1), the second
// spans tile 1002 (u 1..2). Each quad triangulated into 2 triangles.
const UDIM_OBJ = `# generated by udim-view.spec.mjs
v -1 -1 0
v  0 -1 0
v  0  1 0
v -1  1 0
v  0 -1 0
v  1 -1 0
v  1  1 0
v  0  1 0
vt 0 0
vt 1 0
vt 1 1
vt 0 1
vt 1 0
vt 2 0
vt 2 1
vt 1 1
f 1/1 2/2 3/3
f 1/1 3/3 4/4
f 5/5 6/6 7/7
f 5/5 7/7 8/8
`;

const UDIM_MTLX = `<?xml version="1.0"?>
<materialx version="1.39" colorspace="lin_rec709">
  <image name="img_emission" type="color3">
    <input name="file" type="filename" value="albedo.&lt;UDIM&gt;.png" />
  </image>
  <standard_surface name="SR_Udim" type="surfaceshader">
    <input name="base_color" type="color3" value="0, 0, 0" />
    <input name="specular" type="float" value="0" />
    <input name="emission" type="float" value="1" />
    <input name="emission_color" type="color3" nodename="img_emission" />
  </standard_surface>
  <surfacematerial name="Udim" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="SR_Udim" />
  </surfacematerial>
</materialx>`;

test('OBJ spanning UDIM tiles 1001/1002 splits into 2 meshes sharing one program, with distinct per-tile colors', async ({ page, embedURL }) => {
  const redPng = solidColorPngBase64(4, 4, [230, 20, 20]);
  const bluePng = solidColorPngBase64(4, 4, [20, 20, 230]);

  await gotoEngine(page, embedURL);

  const result = await page.evaluate(async ({ xml, objText, redPng, bluePng }) => {
    const env = await window.getMxEnv();
    const doc = env.mx.createDocument();
    await window.mxExclusive(() => env.mx.readFromXmlString(doc, xml));
    if (doc.setDataLibrary) doc.setDataLibrary(env.stdlib);
    const { name: materialName, node: renderable } = window.listDocRenderables(doc)[0];

    await window.loadCustomPreviewGeomFromFile(new File([objText], 'udim-test.obj', { type: 'text/plain' }));

    const canvas = document.createElement('canvas');
    canvas.style.width = '128px';
    canvas.style.height = '128px';
    document.body.appendChild(canvas);

    const view = await window.createMtlxRenderView({
      canvas, mx: env.mx, gen: env.gen, genContext: env.genContext, renderable,
      label: 'udim-view-test', geomName: 'custom', needsLighting: true,
      materialName, isMounted: () => true,
    });

    const b64ToBlob = (b64, type) => {
      const bin = atob(b64);
      const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      return new Blob([bytes], { type });
    };
    const fileMap = {
      'albedo.1001.png': b64ToBlob(redPng, 'image/png'),
      'albedo.1002.png': b64ToBlob(bluePng, 'image/png'),
    };

    // Warm up first: a render before any texture/split touches the scene
    // so the shell's own backdrop/shadow/peel programs are already
    // resident, isolating what the UDIM split itself adds below.
    view.renderNow();
    const programsBefore = view.__debug().renderer.info.programs.length;

    const report = window.bindDroppedTextures(view, fileMap);
    await Promise.all(report.pending || []);
    // The variant texture acquire (2nd tile) may resolve one microtask
    // later than bindDroppedTextures' own pending list; poll briefly.
    const deadline = Date.now() + 5000;
    while (view.getUdimTileCount() < 2 && Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 50));
    }

    const pixels = view.snapshotPixels(128, 128);
    const d = view.__debug();
    // Every tile variant is a material CLONE with byte-identical vs/fs, so
    // r128's program cache (keyed by shader source, not material identity)
    // reuses the SAME compiled program for all of them.
    const programsAfter = d.renderer.info.programs.length;
    // Collect distinct "strongly colored" pixels (either channel
    // dominant), ignoring near-background/gray pixels.
    const colors = new Set();
    for (let i = 0; i < pixels.data.length; i += 4) {
      const r = pixels.data[i], g = pixels.data[i + 1], b = pixels.data[i + 2];
      if (r > 150 && r > g + 40 && r > b + 40) colors.add('red');
      if (b > 150 && b > g + 40 && b > r + 40) colors.add('blue');
    }

    return {
      udimTileCount: view.getUdimTileCount(),
      childMeshCount: d.mesh.children.length,
      programsBefore, programsAfter,
      colors: Array.from(colors),
      notices: view.notices,
    };
  }, { xml: UDIM_MTLX, objText: UDIM_OBJ, redPng, bluePng });

  expect(result.udimTileCount).toBe(2);
  expect(result.childMeshCount).toBe(1); // mesh itself keeps the lowest tile (1001), 1 child for 1002
  expect(result.programsAfter - result.programsBefore).toBe(0); // the split adds zero new programs
  expect(result.colors.sort()).toEqual(['blue', 'red']);
});

test('the sphere still binds tile 1001 (built-in geometry is unaffected by the split)', async ({ page, embedURL }) => {
  const redPng = solidColorPngBase64(4, 4, [230, 20, 20]);
  const bluePng = solidColorPngBase64(4, 4, [20, 20, 230]);

  await gotoEngine(page, embedURL);

  const result = await page.evaluate(async ({ xml, redPng, bluePng }) => {
    const env = await window.getMxEnv();
    const doc = env.mx.createDocument();
    await window.mxExclusive(() => env.mx.readFromXmlString(doc, xml));
    if (doc.setDataLibrary) doc.setDataLibrary(env.stdlib);
    const { name: materialName, node: renderable } = window.listDocRenderables(doc)[0];

    const canvas = document.createElement('canvas');
    document.body.appendChild(canvas);
    const view = await window.createMtlxRenderView({
      canvas, mx: env.mx, gen: env.gen, genContext: env.genContext, renderable,
      label: 'udim-sphere-test', geomName: 'sphere', needsLighting: true,
      materialName, isMounted: () => true,
    });

    const b64ToBlob = (b64, type) => {
      const bin = atob(b64);
      const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      return new Blob([bytes], { type });
    };
    const fileMap = {
      'albedo.1001.png': b64ToBlob(redPng, 'image/png'),
      'albedo.1002.png': b64ToBlob(bluePng, 'image/png'),
    };
    const report = window.bindDroppedTextures(view, fileMap);
    await Promise.all(report.pending || []);

    return { udimFirstTile: report.udimFirstTile, boundTexture: view.uniforms.u_img_emission_file ? true : Object.keys(view.uniforms).some((k) => /emission/i.test(k)) };
  }, { xml: UDIM_MTLX, redPng, bluePng });

  expect(result.udimFirstTile).toEqual(['albedo.<UDIM>.png']);
});
