// Runtime theme data: seeds, themes (role -> hex) and non-color params. js/gen/theme-tokens.css is generated from it.
// Per-token notes and contrast pairs live in scripts/theme-tokens-meta.mjs (Node only, never shipped).
// UMD: window.MTLX_THEME_TOKENS in the browser, module.exports under Node (build step, Electron).
// themes.<name> may be a partial map: a missing token falls back to the dark value.
(function (root, factory) {
    const data = factory();
    if (typeof module === 'object' && module.exports) module.exports = data;
    else root.MTLX_THEME_TOKENS = data;
})(typeof self !== 'undefined' ? self : this, function () {
    'use strict';

    const seeds = {
        dark: { background: '#111827', foreground: '#f3f4f6', accent: '#3b82f6' },
        light: { background: '#f3f4f6', foreground: '#111827', accent: '#2563eb' },
    };

    // typeFallback feeds typeColor()'s hsl() for unknown types. graph.minimapMaskAlpha: MiniMap mask opacity.
    // alpha.hudPopover: opacity of popovers over renders; alpha.accentFillTranslucent: primary-button fill opacity.
    const params = {
        dark: { typeFallback: { saturation: 65, lightness: 62 }, graph: { minimapMaskAlpha: 0.75 }, alpha: { hudPopover: 0.95, accentFillTranslucent: 0.7 } },
        light: { typeFallback: { saturation: 65, lightness: 34 }, graph: { minimapMaskAlpha: 0.5 }, alpha: { hudPopover: 1, accentFillTranslucent: 1 } },
    };

    const dark = {
        'surface-base': '#111827',
        'surface-raised': '#1f2937',
        'surface-sunken': '#111827',
        'chrome': '#111827',
        'control': '#1f2937',
        'chip': '#374151',
        'stage': '#111827',
        'stage-fg-muted': '#9ca3af',
        'stage-fg-subtle': '#6b7280',
        'veil': '#111827',
        'scrim': '#030712',
        'hover': '#374151',
        'hover-subtle': '#1f2937',
        'hover-strong': '#4b5563',
        'pressed': '#374151',
        'line': '#374151',
        'line-subtle': '#1f2937',
        'line-control': '#374151',
        'line-strong': '#4b5563',
        'line-heavy': '#6b7280',
        'fg-strong': '#ffffff',
        'fg': '#f3f4f6',
        'fg-soft': '#e5e7eb',
        'fg-secondary': '#d1d5db',
        'fg-muted': '#9ca3af',
        'fg-subtle': '#6b7280',
        'fg-faint': '#4b5563',
        'fg-disabled': '#4b5563',
        'fg-inverse': '#111827',
        'accent-base': '#3b82f6',
        'accent-fill': '#2563eb',
        'accent-fill-hover': '#3b82f6',
        'accent-fill-pressed': '#1d4ed8',
        'accent-fill-translucent': '#2563eb',
        'accent-fill-translucent-hover': '#3b82f6',
        'accent-wash': '#3b82f6',
        'accent-fg': '#60a5fa',
        'accent-fg-strong': '#93c5fd',
        'accent-fg-bright': '#bfdbfe',
        'on-accent': '#ffffff',
        'on-accent-muted': '#dbeafe',
        'accent-text-on-tint': '#dbeafe',
        'selection': '#2563eb',
        'focus': '#3b82f6',
        'progress': '#60a5fa',
        'drop-target': '#172554',
        'hover-accent': '#1e3a8a',
        'success': '#4ade80',
        'success-text': '#86efac',
        'success-hue': '#22c55e',
        'success-fill': '#16a34a',
        'success-bg': '#052e16',
        'success-border': '#15803d',
        'warning': '#fcd34d',
        'warning-text': '#fde68a',
        'warning-text-strong': '#fef3c7',
        'warning-marker': '#fbbf24',
        'warning-hue': '#f59e0b',
        'warning-bg': '#78350f',
        'warning-border': '#b45309',
        'error': '#f87171',
        'error-text': '#fca5a5',
        'error-hue': '#ef4444',
        'error-fill': '#dc2626',
        'error-fill-hover': '#b91c1c',
        'error-bg': '#450a0a',
        'error-border': '#991b1b',
        'info': '#7dd3fc',
        'info-text': '#bfdbfe',
        'info-bg': '#172554',
        'info-border': '#1e40af',
        'experimental': '#fcd34d',
        'experimental-hue': '#f59e0b',
        'hud': '#111827',
        'hud-raised': '#1f2937',
        'hud-line': '#4b5563',
        'hud-fg': '#d1d5db',
        'hud-fg-muted': '#9ca3af',
        'hud-fg-strong': '#f3f4f6',
        'hud-hover': '#374151',
        'hud-selection': '#60a5fa',
        'shadow': '#000000',
        'scrollbar-track': '#1f2937',
        'scrollbar-thumb': '#374151',
        'brand-mark': '#ffffff',
        'brand-accent': '#60a5fa',
        'brand-logo-inner': '#ffffff',
        'code-fg': '#d1d5db',
        'code-muted': '#6b7280',
        'code-name': '#60a5fa',
        'code-attr': '#9ca3af',
        'code-string': '#4ade80',
        'code-inline-bg': '#374151',
        'code-inline-fg': '#fcd34d',
        'code-block-bg': '#0b1120',
        'graph-canvas': '#111827',
        'graph-grid': '#374151',
        'builder-stage': '#0b1220',
        'builder-stage-grid': '#6b7280',
        'graph-edge-draft': '#60a5fa',
        'graph-edge-selected': '#3b82f6',
        'graph-node': '#1f2937',
        'graph-node-header': '#111827',
        'graph-node-line': '#4b5563',
        'graph-node-line-iface': '#6b7280',
        'graph-node-selected': '#3b82f6',
        'graph-minimap-bg': '#1f2937',
        'graph-minimap-mask': '#111827',
        'graph-minimap-stroke': '#111827',
        'type-boolean': '#d2372b',
        'type-bsdf': '#2e7d32',
        'type-color3': '#fdd835',
        'type-color4': '#f4511e',
        'type-displacementshader': '#8d6e63',
        'type-edf': '#cddc39',
        'type-filename': '#90a4ae',
        'type-float': '#3949ab',
        'type-integer': '#8e24aa',
        'type-lightshader': '#ff934f',
        'type-material': '#ff404f',
        'type-matrix33': '#cfd8dc',
        'type-matrix44': '#546e7a',
        'type-string': '#d7c4a3',
        'type-surfaceshader': '#00897b',
        'type-vector2': '#5c6bc0',
        'type-vector3': '#b388ff',
        'type-vector4': '#ec407a',
        'type-vdf': '#9ccc65',
        'type-volumeshader': '#00bcd4',
        'type-node': '#a1887f',
        'type-nodegraph': '#854d0e',
        'type-untyped': '#94a3b8',
        'native-window-bg': '#0b0f19',
        'native-titlebar': '#111827',
        'native-titlebar-symbol': '#e5e7eb',
        'surface-deep': '#030712',
        'scrim-alt': '#000000',
        'on-accent-soft': '#f3f4f6',
        'success-border-muted': '#166534',
        'warning-bg-strong': '#92400e',
        'warning-border-alt': '#d97706',
        'error-text-strong': '#fecaca',
        'error-bg-strong': '#7f1d1d',
        'error-border-strong': '#b91c1c',
        'info-border-alt': '#1d4ed8',
        'notice-bg': '#1e293b',
        'notice-line': '#475569',
        'notice-text': '#e2e8f0',
        'notice-text-strong': '#f1f5f9',
        'experimental-fill': '#d97706',
        'code-inline-fg-alt': '#fca5a5',
        'code-block-bg-alt': '#0f172a',
    };

    // Palette rationale: docs/local/theme-tokens.md. Any token missing here falls back to dark.
    const light = {
        'surface-base': '#f3f4f6',
        'surface-raised': '#ffffff',
        'surface-sunken': '#f9fafb',
        'chrome': '#f3f4f6',
        'control': '#ffffff',
        'chip': '#e5e7eb',
        'stage': '#f3f4f6',
        'stage-fg-muted': '#374151',
        'stage-fg-subtle': '#4b5563',
        'veil': '#f9fafb',
        'scrim': '#334155',
        'hover': '#e5e7eb',
        'hover-subtle': '#eaecf0',
        'hover-strong': '#d1d5db',
        'pressed': '#e2e5e9',
        'line': '#d1d5db',
        'line-subtle': '#e5e7eb',
        'line-control': '#848b98',
        'line-strong': '#7b8290',
        'line-heavy': '#6b7280',
        'fg-strong': '#030712',
        'fg': '#111827',
        'fg-soft': '#1f2937',
        'fg-secondary': '#374151',
        'fg-muted': '#4b5563',
        'fg-subtle': '#6b7280',
        'fg-faint': '#848b98',
        'fg-disabled': '#9ca3af',
        'fg-inverse': '#f3f4f6',
        'accent-base': '#3b82f6',
        'accent-fill': '#2563eb',
        'accent-fill-hover': '#1d4ed8',
        'accent-fill-pressed': '#1e40af',
        'accent-fill-translucent': '#2563eb',
        'accent-fill-translucent-hover': '#1d4ed8',
        'accent-wash': '#3b82f6',
        'accent-fg': '#2563eb',
        'accent-fg-strong': '#1d4ed8',
        'accent-fg-bright': '#1e40af',
        'on-accent': '#ffffff',
        'on-accent-muted': '#eff6ff',
        'accent-text-on-tint': '#1e40af',
        'selection': '#3b82f6',
        'focus': '#2563eb',
        'progress': '#2563eb',
        'drop-target': '#bfdbfe',
        'hover-accent': '#93c5fd',
        'success': '#15803d',
        'success-text': '#166534',
        'success-hue': '#16a34a',
        'success-fill': '#15803d',
        'success-bg': '#bbf7d0',
        'success-border': '#16a34a',
        'warning': '#b45309',
        'warning-text': '#92400e',
        'warning-text-strong': '#78350f',
        'warning-marker': '#d97706',
        'warning-hue': '#f59e0b',
        'warning-bg': '#fde68a',
        'warning-border': '#d97706',
        'error': '#dc2626',
        'error-text': '#991b1b',
        'error-hue': '#ef4444',
        'error-fill': '#dc2626',
        'error-fill-hover': '#b91c1c',
        'error-bg': '#fee2e2',
        'error-border': '#f87171',
        'info': '#0369a1',
        'info-text': '#1e40af',
        'info-bg': '#bfdbfe',
        'info-border': '#60a5fa',
        'experimental': '#b45309',
        'experimental-hue': '#f59e0b',
        'hud': '#f9fafb',
        'hud-raised': '#ffffff',
        'hud-line': '#848b98',
        'hud-fg': '#1f2937',
        'hud-fg-muted': '#374151',
        'hud-fg-strong': '#030712',
        'hud-hover': '#e5e7eb',
        'hud-selection': '#60a5fa',
        'shadow': '#64748b',
        'scrollbar-track': '#f3f4f6',
        'scrollbar-thumb': '#848b98',
        'brand-mark': '#111827',
        'brand-accent': '#2563eb',
        'brand-logo-inner': '#ffffff',
        'code-fg': '#1f2937',
        'code-muted': '#6b7280',
        'code-name': '#1d4ed8',
        'code-attr': '#4b5563',
        'code-string': '#15803d',
        'code-inline-bg': '#e5e7eb',
        'code-inline-fg': '#b45309',
        'code-block-bg': '#f5f7fa',
        'graph-canvas': '#f3f4f6',
        'graph-grid': '#a1a8b3',
        'builder-stage': '#f3f4f6',
        'builder-stage-grid': '#a1a8b3',
        'graph-edge-draft': '#3b82f6',
        'graph-edge-selected': '#2563eb',
        'graph-node': '#ffffff',
        'graph-node-header': '#eef0f3',
        'graph-node-line': '#848b98',
        'graph-node-line-iface': '#6b7280',
        'graph-node-selected': '#2563eb',
        'graph-minimap-bg': '#ffffff',
        'graph-minimap-mask': '#d1d5db',
        'graph-minimap-stroke': '#ffffff',
        'type-boolean': '#d2372b',
        'type-bsdf': '#2e7d32',
        'type-color3': '#a28915',
        'type-color4': '#e64a19',
        'type-displacementshader': '#8d6e63',
        'type-edf': '#869112',
        'type-filename': '#6e8590',
        'type-float': '#3949ab',
        'type-integer': '#8e24aa',
        'type-lightshader': '#d56d23',
        'type-material': '#e8313f',
        'type-matrix33': '#37474f',
        'type-matrix44': '#546e7a',
        'type-string': '#998768',
        'type-surfaceshader': '#00897b',
        'type-vector2': '#5c6bc0',
        'type-vector3': '#9c70e8',
        'type-vector4': '#ec407a',
        'type-vdf': '#6a972e',
        'type-volumeshader': '#1b98aa',
        'type-node': '#9e857c',
        'type-nodegraph': '#854d0e',
        'type-untyped': '#7d8ca0',
        'native-window-bg': '#f3f4f6',
        'native-titlebar': '#f3f4f6',
        'native-titlebar-symbol': '#374151',
        'surface-deep': '#f9fafb',
        'scrim-alt': '#334155',
        'on-accent-soft': '#ffffff',
        'success-border-muted': '#16a34a',
        'warning-bg-strong': '#fcd34d',
        'warning-border-alt': '#d97706',
        'error-text-strong': '#991b1b',
        'error-bg-strong': '#fca5a5',
        'error-border-strong': '#f87171',
        'info-border-alt': '#60a5fa',
        'notice-bg': '#ffffff',
        'notice-line': '#7b8290',
        'notice-text': '#1f2937',
        'notice-text-strong': '#111827',
        'experimental-fill': '#fde68a',
        'code-inline-fg-alt': '#b45309',
        'code-block-bg-alt': '#f5f7fa',
    };

    const themes = { dark: dark, light: light };

    // [id, label, base, group, contrast level, hosts?] in menu order; ids beyond dark and light are lazy presets (js/gen/themes/).
    const registry = [
        ['vscode', 'Match VS Code', 'auto', 'standard', 'AA', ['vscode']],
        ['light', 'Light', 'light', 'standard', 'AA'],
        ['dark', 'Dark', 'dark', 'standard', 'AA'],
        ['hc-dark', 'High contrast dark', 'dark', 'accessibility', 'AAA'],
        ['hc-light', 'High contrast light', 'light', 'accessibility', 'AAA'],
        ['dim', 'Dim', 'dark', 'presets', 'AA'],
        ['paper', 'Paper', 'light', 'presets', 'AA'],
    ].map(function (r) { const e = { id: r[0], label: r[1], base: r[2], group: r[3], contrast: r[4] }; if (r[5]) e.hosts = r[5]; return e; });

    return { version: 1, seeds, params, themes, registry };
});
