// Runtime theme data: seeds, themes (role -> hex) and non-color params. js/gen/theme-tokens.css is generated from it.
// Per-token notes and contrast pairs live in scripts/theme-tokens-meta.mjs (Node only, never shipped).
// UMD: window.MTLX_THEME_TOKENS in the browser, module.exports under Node (build step, Electron).
// themes.<name> may be a partial map: a missing token falls back to the dark value for now.
(function (root, factory) {
    const data = factory();
    if (typeof module === 'object' && module.exports) module.exports = data;
    else root.MTLX_THEME_TOKENS = data;
})(typeof self !== 'undefined' ? self : this, function () {
    'use strict';

    const seeds = {
        dark: { background: '#111827', foreground: '#f3f4f6', accent: '#3b82f6' },
    };

    // typeFallback feeds typeColor()'s hsl() for unknown types.
    const params = {
        dark: { typeFallback: { saturation: 65, lightness: 62 } },
    };

    const themes = {
        dark: {
            'surface-base': '#111827',
            'surface-raised': '#1f2937',
            'surface-sunken': '#111827',
            'chrome': '#111827',
            'control': '#1f2937',
            'chip': '#374151',
            'stage': '#111827',
            'veil': '#111827',
            'scrim': '#030712',
            'hover': '#374151',
            'hover-subtle': '#1f2937',
            'hover-strong': '#4b5563',
            'pressed': '#374151',
            'line': '#374151',
            'line-subtle': '#1f2937',
            'line-strong': '#4b5563',
            'line-heavy': '#6b7280',
            'fg-strong': '#ffffff',
            'fg': '#f3f4f6',
            'fg-soft': '#e5e7eb',
            'fg-secondary': '#d1d5db',
            'fg-muted': '#9ca3af',
            'fg-subtle': '#6b7280',
            'fg-faint': '#4b5563',
            'fg-disabled': '#4b5563',
            'fg-inverse': '#111827',
            'accent-base': '#3b82f6',
            'accent-fill': '#2563eb',
            'accent-fill-hover': '#3b82f6',
            'accent-fill-pressed': '#1d4ed8',
            'accent-wash': '#3b82f6',
            'accent-fg': '#60a5fa',
            'accent-fg-strong': '#93c5fd',
            'accent-fg-bright': '#bfdbfe',
            'on-accent': '#ffffff',
            'on-accent-muted': '#dbeafe',
            'selection': '#2563eb',
            'focus': '#3b82f6',
            'progress': '#60a5fa',
            'drop-target': '#172554',
            'hover-accent': '#1e3a8a',
            'success': '#4ade80',
            'success-text': '#86efac',
            'success-hue': '#22c55e',
            'success-fill': '#16a34a',
            'success-bg': '#052e16',
            'success-border': '#15803d',
            'warning': '#fcd34d',
            'warning-text': '#fde68a',
            'warning-text-strong': '#fef3c7',
            'warning-marker': '#fbbf24',
            'warning-hue': '#f59e0b',
            'warning-bg': '#78350f',
            'warning-border': '#b45309',
            'error': '#f87171',
            'error-text': '#fca5a5',
            'error-hue': '#ef4444',
            'error-fill': '#dc2626',
            'error-fill-hover': '#b91c1c',
            'error-bg': '#450a0a',
            'error-border': '#991b1b',
            'info': '#7dd3fc',
            'info-text': '#bfdbfe',
            'info-bg': '#172554',
            'info-border': '#1e40af',
            'experimental': '#fcd34d',
            'experimental-hue': '#f59e0b',
            'hud': '#111827',
            'hud-raised': '#1f2937',
            'hud-line': '#4b5563',
            'hud-fg': '#d1d5db',
            'hud-fg-muted': '#9ca3af',
            'hud-fg-strong': '#f3f4f6',
            'hud-hover': '#374151',
            'hud-selection': '#60a5fa',
            'shadow': '#000000',
            'scrollbar-track': '#1f2937',
            'scrollbar-thumb': '#374151',
            'brand-mark': '#ffffff',
            'brand-accent': '#60a5fa',
            'code-fg': '#d1d5db',
            'code-muted': '#6b7280',
            'code-name': '#60a5fa',
            'code-attr': '#9ca3af',
            'code-string': '#4ade80',
            'code-inline-bg': '#374151',
            'code-inline-fg': '#fcd34d',
            'code-block-bg': '#0b1120',
            'graph-canvas': '#111827',
            'graph-grid': '#374151',
            'graph-edge-draft': '#60a5fa',
            'graph-edge-selected': '#3b82f6',
            'graph-node': '#1f2937',
            'graph-node-header': '#111827',
            'graph-node-line': '#4b5563',
            'graph-node-line-iface': '#6b7280',
            'graph-node-selected': '#3b82f6',
            'graph-minimap-bg': '#1f2937',
            'graph-minimap-mask': '#111827',
            'graph-minimap-stroke': '#111827',
            'type-boolean': '#d2372b',
            'type-bsdf': '#2e7d32',
            'type-color3': '#fdd835',
            'type-color4': '#f4511e',
            'type-displacementshader': '#8d6e63',
            'type-edf': '#cddc39',
            'type-filename': '#90a4ae',
            'type-float': '#3949ab',
            'type-integer': '#8e24aa',
            'type-lightshader': '#ff934f',
            'type-material': '#ff404f',
            'type-matrix33': '#cfd8dc',
            'type-matrix44': '#546e7a',
            'type-string': '#d7c4a3',
            'type-surfaceshader': '#00897b',
            'type-vector2': '#5c6bc0',
            'type-vector3': '#b388ff',
            'type-vector4': '#ec407a',
            'type-vdf': '#9ccc65',
            'type-volumeshader': '#00bcd4',
            'type-node': '#a1887f',
            'type-nodegraph': '#854d0e',
            'type-untyped': '#94a3b8',
            'native-window-bg': '#0b0f19',
            'native-titlebar': '#111827',
            'native-titlebar-symbol': '#e5e7eb',
            'surface-deep': '#030712',
            'scrim-alt': '#000000',
            'on-accent-soft': '#f3f4f6',
            'success-border-muted': '#166534',
            'warning-bg-strong': '#92400e',
            'warning-border-alt': '#d97706',
            'error-text-strong': '#fecaca',
            'error-bg-strong': '#7f1d1d',
            'error-border-strong': '#b91c1c',
            'info-border-alt': '#1d4ed8',
            'notice-bg': '#1e293b',
            'notice-line': '#475569',
            'notice-text': '#e2e8f0',
            'notice-text-strong': '#f1f5f9',
            'experimental-fill': '#d97706',
            'code-inline-fg-alt': '#fca5a5',
            'code-block-bg-alt': '#0f172a',
        },
    };

    return { version: 1, seeds, params, themes };
});
