// scripts/vendor-deps.mjs
//
// Registry of every third-party asset collected into vendor/ by
// `npm run vendor` (scripts/vendor.mjs). See docs/BUILDING.md for the
// field reference and how to add a dependency. Nothing else belongs here.

export const VENDOR_DEPS = [
  {
    id: "react",
    name: "React",
    source: { npm: "react", files: { "umd/react.production.min.js": "react.production.min.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/facebook/react/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "react-dom",
    name: "React",
    dir: "react",
    source: { npm: "react-dom", files: { "umd/react-dom.production.min.js": "react-dom.production.min.js" } },
    license: { url: "https://github.com/facebook/react/blob/HEAD/LICENSE" },
  },
  {
    id: "babel",
    name: "Babel",
    source: { npm: "@babel/standalone", files: { "babel.min.js": "babel.min.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/babel/babel/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "three",
    name: "three.js",
    source: {
      npm: "three",
      files: {
        "build/three.min.js": "three.min.js",
        "examples/js/loaders/RGBELoader.js": "RGBELoader.js",
        "examples/js/loaders/GLTFLoader.js": "GLTFLoader.js",
        "examples/js/loaders/OBJLoader.js": "OBJLoader.js",
        "examples/js/loaders/PLYLoader.js": "PLYLoader.js",
        "examples/js/controls/OrbitControls.js": "OrbitControls.js",
        "examples/js/loaders/DRACOLoader.js": "DRACOLoader.js",
        "examples/js/libs/draco/gltf/draco_wasm_wrapper.js": "draco/draco_wasm_wrapper.js",
        // WASM-only, like the KaTeX woff2-only filter below: the app hard
        // requires WebAssembly anyway, so the JS fallback decoder is skipped.
        "examples/js/libs/draco/gltf/draco_decoder.wasm": "draco/draco_decoder.wasm",
        // vendor/three/KTX2Loader.js itself is NOT vendored here: it is
        // generated by scripts/gen-ktx2-loader.mjs from the jsm KTX2Loader
        // stack, since r128's examples/js tree ships no plain-script one.
        "examples/js/libs/basis/basis_transcoder.js": "basis/basis_transcoder.js",
        "examples/js/libs/basis/basis_transcoder.wasm": "basis/basis_transcoder.wasm",
        LICENSE: "LICENSE.txt",
      },
    },
    license: { url: "https://github.com/mrdoob/three.js/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "three-147",
    name: "three.js",
    dir: "three",
    // npm alias (three-147: npm:three@0.147.0): only this version's fflate
    // build is used, the rest of the three@0.147.0 tree is left uncollected.
    source: { npm: "three-147", files: { "examples/js/libs/fflate.min.js": "fflate.min.js" } },
    license: { url: "https://github.com/mrdoob/three.js/blob/HEAD/LICENSE" },
  },
  {
    id: "draco",
    name: "Draco",
    dir: "three/draco",
    version: "1.5.7",
    source: {
      files: [{ url: "https://raw.githubusercontent.com/google/draco/{version}/LICENSE", sha256: "d3709b0fb4b8a94bbb1d02b8a2e484f258b0d9c5c5a01f940391f3fe662cd1a4", as: "LICENSE.txt" }],
    },
    license: { url: "https://github.com/google/draco/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "katex",
    name: "KaTeX",
    source: {
      npm: "katex",
      files: {
        "dist/katex.min.css": "katex.min.css",
        "dist/katex.min.js": "katex.min.js",
        // katex.min.css references url(fonts/...) relative to itself, and
        // only .woff2 is vendored (the app needs WebAssembly anyway).
        "dist/fonts/*.woff2": "fonts/",
        LICENSE: "LICENSE.txt",
      },
    },
    license: { url: "https://github.com/KaTeX/KaTeX/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "jszip",
    name: "JSZip",
    source: { npm: "jszip", files: { "dist/jszip.min.js": "jszip.min.js", "LICENSE.markdown": "LICENSE.markdown" } },
    license: { url: "https://github.com/Stuk/jszip/blob/HEAD/LICENSE.markdown", file: "LICENSE.markdown" },
    module: { entry: "jszip.min.js", kind: "script", global: "JSZip" },
  },
  {
    id: "utif",
    name: "UTIF.js",
    source: { npm: "utif", files: { "UTIF.js": "UTIF.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/photopea/UTIF.js/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "pako",
    name: "pako",
    source: {
      npm: "pako",
      // inflate-only UMD build: UTIF.js's compression-8 path calls
      // pako.inflate at runtime, the full build also bundles an unused
      // deflate encoder, so only the smaller inflate-only build ships.
      files: { "dist/pako_inflate.min.js": "pako_inflate.min.js", LICENSE: "LICENSE.txt" },
    },
    license: { url: "https://github.com/nodeca/pako/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "reactflow",
    name: "React Flow",
    source: { npm: "reactflow", files: { "dist/style.css": "style.css", "dist/umd/index.js": "index.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/xyflow/xyflow/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "dagre",
    name: "Dagre",
    source: { npm: "dagre", files: { "dist/dagre.min.js": "dagre.min.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/dagrejs/dagre/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "highlightjs",
    name: "highlight.js",
    // @highlightjs/cdn-assets mirrors the cdnjs single-file build; the
    // plain highlight.js package ships an unbundled ESM tree instead.
    source: { npm: "@highlightjs/cdn-assets", files: { "highlight.min.js": "highlight.min.js", "languages/xml.min.js": "xml.min.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/highlightjs/highlight.js/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    version: "3.4.17",
    source: {
      files: [
        { url: "https://cdn.tailwindcss.com/{version}", sha256: "176e894661aa9cdc9a5cba6c720044cbbf7b8bd80d1c9a142a7c24b1b6c50d15", as: "tailwind-play.min.js" },
        // Not on npm either: fetched from the GitHub tag matching the
        // pinned Play CDN version above and verified the same way.
        { url: "https://raw.githubusercontent.com/tailwindlabs/tailwindcss/v{version}/LICENSE", sha256: "60e0b68c0f35c078eef3a5d29419d0b03ff84ec1df9c3f9d6e39a519a5ae7985", as: "LICENSE.txt" },
      ],
    },
    license: { url: "https://github.com/tailwindlabs/tailwindcss/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "basis-encoder",
    name: "Basis Universal",
    // Not on npm; pinned to the default branch HEAD at the time this was
    // vendored. Re-pin via `git ls-remote .../basis_universal.git HEAD`.
    version: "99f52d63aa6799cbdaecfe977111dc5ec3b31d47",
    source: {
      files: [
        { url: "https://raw.githubusercontent.com/BinomialLLC/basis_universal/{version}/webgl/encoder/build/basis_encoder.js", sha256: "d225ce1e7012609bcfbe338351c8778d95eb1c19d404314d513b2b2df94a6ffb", as: "basis_encoder.js" },
        { url: "https://raw.githubusercontent.com/BinomialLLC/basis_universal/{version}/webgl/encoder/build/basis_encoder.wasm", sha256: "48d4e39ccaa1e290a17d00c13b353a728227bb439108d5e6c944fe6ab80552db", as: "basis_encoder.wasm" },
        { url: "https://raw.githubusercontent.com/BinomialLLC/basis_universal/{version}/LICENSE", sha256: "065fcf48d6af21c0b75e23be5ed5753aee75c892e1c2cf178fa6736305614a5c", as: "LICENSE.txt" },
      ],
    },
    license: { url: "https://github.com/BinomialLLC/basis_universal/blob/{version}/LICENSE", file: "LICENSE.txt" },
    // Only scripts/cook-textures.mjs uses it; never loaded at runtime.
    vscode: false,
  },
  {
    id: "usd-webview-bindings",
    name: "OpenUSD WebView Bindings",
    version: "2026.10.1",
    fetchOnly: true,
    // Patched build published by the USDBindings release (joaovbs96/
    // USDBindings), not raw upstream usd-wg-webview. It also carries the
    // OpenUSD, MaterialX and usd-wg-webview licences (LICENSES.txt).
    source: {
      files: [
        { url: "https://github.com/joaovbs96/USDBindings/releases/download/v{version}/usdWebViewBindings.js", sha256: "1bd9d2349526e1fbb21a5f31ca2736efeeee04617c825e4e8f2c7094f9bcb6fc", as: "usdWebViewBindings.js" },
        { url: "https://github.com/joaovbs96/USDBindings/releases/download/v{version}/usdWebViewBindingsModule.js", sha256: "d8795ca7427116a2a6508d5e3df7459c36bb6482369186ec44a9b533ee65130d", as: "usdWebViewBindingsModule.js" },
        { url: "https://github.com/joaovbs96/USDBindings/releases/download/v{version}/usdWebViewBindingsModule.wasm", sha256: "f62a88652a9d23eee80072eab23bf18f5a08dc931099b36f9bd856f2ca82599c", as: "usdWebViewBindingsModule.wasm" },
        { url: "https://github.com/joaovbs96/USDBindings/releases/download/v{version}/LICENSES.txt", sha256: "9b3423366cbda9b07e95910c263c91a0866fbe349826398978ca7f4c8217fb11", as: "LICENSE" },
      ],
    },
    license: { url: "https://github.com/joaovbs96/USDBindings/releases/tag/v{version}", file: "LICENSE" },
  },
  {
    id: "mxslc",
    name: "ShadingLanguageX compiler (mxslc)",
    version: "0.3.2",
    source: {
      zip: "https://github.com/jakethorn/ShadingLanguageX/releases/download/mxslcxx-{version}/mxslc_JsMxslc_package.zip",
      sha256: "b732301f4ea9f95d2e7c1469e0b68ec1e1e04368fa134ee094451bd05e5fe36f",
    },
    license: { url: "https://github.com/jakethorn/ShadingLanguageX/blob/mxslcxx-{version}/LICENSE", file: "LICENSE" },
    fetchOnly: true,
    vscode: false,
    module: { entry: "JsMxslc.js", kind: "emscripten-esm" },
  },
  {
    id: "xml-formatter",
    name: "xml-formatter",
    // vscode_extension/src/formatter.js's .mtlx re-indent formatter, loaded
    // through its own contained loader (its require('xml-parser-xo') is
    // remapped there) -- no nested node_modules (that would land under
    // .gitignore's blanket "node_modules/" rule and never get committed).
    source: { npm: "xml-formatter", files: { "dist/cjs/index.js": "index.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/chrisbottin/xml-formatter/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
  {
    id: "xml-parser-xo",
    name: "xml-parser-xo",
    // xml-formatter's one runtime dependency. Flat, own top-level vendor
    // dir (see the loader note above), not nested inside xml-formatter's.
    source: { npm: "xml-parser-xo", files: { "dist/cjs/index.js": "index.js", LICENSE: "LICENSE.txt" } },
    license: { url: "https://github.com/chrisbottin/xml-parser/blob/HEAD/LICENSE", file: "LICENSE.txt" },
  },
];
